services:
    api:
        container_name: api
        build: ./backend
        ports:
            - 3000:3000
        networks:
            - to-do-network
        restart: unless-stopped

    frontend:
        container_name: SPA
        build: ./frontend
        ports:
            - 8080:80
        networks:
            - to-do-network

    database:
        container_name: db
        build: ./db
        networks:
            - to-do-network
        ports:
            - 1433:1433

networks:
    to-do-network:
